### PR TITLE
add regenerate-all to the dracut command 

### PR DESCRIPTION
**Pull request by lessfoobar**
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/configuring-automated-unlocking-of-encrypted-volumes-using-policy-based-decryption_security-hardening#configuring-manual-enrollment-of-volumes-using-clevis_configuring-automated-unlocking-of-encrypted-volumes-using-policy-based-decryption

section 9.9 point 5 recommends using dracut -f plus --regenerate-all sometimes the systems can not be booted

### CODE REVIEW

**Comment by richm** [comment]
[citest commit:1f74c3cf042ce7fd439e3c6970bec09e8c5f41a4]

**Comment by richm** [comment]
lgtm - @sergio-correia ?

**Comment by sergio-correia** [comment]
> lgtm - @sergio-correia ?

lgtm as well, but I would also update `RedHat_9.yml` with the same change.

**Comment by richm** [comment]
ping - any update?

**Comment by sergio-correia** [comment]
@lessfoobar: are you planning on updating this PR to also update `RedHat_9.yml`? It would be great if we could merge this fix.

**Comment by lessfoobar** [comment]
there were new changes to the RHEL docu thus the second update.

**Comment by richm** [comment]
[citest pending]

**Pull request merged**
