### PR TITLE
Fix issues found by ansible-test and linters - enable all tests on all repos - remove suppressions

### PR DESCRIPTION
**Pull request by nhosoi**
- Cleaning up ansible-lint errors.
- Cleaning up ansible-test errors.

### CODE REVIEW

**Comment by richm** [comment]
please also fix the lint error in  tests/tests_passphrase_temporary_keyfile.yml
you can probably use `mode: preserve` there unless it requires a stricter permission

**Comment by nhosoi** [comment]
> please also fix the lint error in tests/tests_passphrase_temporary_keyfile.yml
> you can probably use `mode: preserve` there unless it requires a stricter permission

Thank you, @richm. I think this is what you suggest. I'm updating the pr.
```
--- a/tests/tests_passphrase_temporary_keyfile.yml
+++ b/tests/tests_passphrase_temporary_keyfile.yml
@@ -35,6 +35,7 @@
           copy:
             src: "{{ nbde_client_test_encryption_key_src }}"
             dest: "{{ nbde_client_test_encryption_key_src }}"
+            mode: preserve
```
Without the fix I was getting `congratulations` from the full tox run. Do you know why the mode check is skipped for me?
```
___________________________________ summary ____________________________________
  flake8: commands succeeded
  py38: commands succeeded
  py37: commands succeeded
  py27: commands succeeded
  pylint: commands succeeded
  custom: commands succeeded
  black: commands succeeded
  shellcheck: commands succeeded
SKIPPED:  py26: InterpreterNotFound: python2.6
  ansible-lint: commands succeeded
  yamllint: commands succeeded
  py36: commands succeeded
  collection: commands succeeded
  ansible-test: commands succeeded
  congratulations :)

```

**Comment by richm** [comment]
> > please also fix the lint error in tests/tests_passphrase_temporary_keyfile.yml
> > you can probably use `mode: preserve` there unless it requires a stricter permission
> 
> Thank you, @richm. I think this is what you suggest. I'm updating the pr.
> 
> ```
> --- a/tests/tests_passphrase_temporary_keyfile.yml
> +++ b/tests/tests_passphrase_temporary_keyfile.yml
> @@ -35,6 +35,7 @@
>            copy:
>              src: "{{ nbde_client_test_encryption_key_src }}"
>              dest: "{{ nbde_client_test_encryption_key_src }}"
> +            mode: preserve
> ```
> 
> Without the fix I was getting `congratulations` from the full tox run. Do you know why the mode check is skipped for me?

No, I don't know.

> 
> ```
> ___________________________________ summary ____________________________________
>   flake8: commands succeeded
>   py38: commands succeeded
>   py37: commands succeeded
>   py27: commands succeeded
>   pylint: commands succeeded
>   custom: commands succeeded
>   black: commands succeeded
>   shellcheck: commands succeeded
> SKIPPED:  py26: InterpreterNotFound: python2.6
>   ansible-lint: commands succeeded
>   yamllint: commands succeeded
>   py36: commands succeeded
>   collection: commands succeeded
>   ansible-test: commands succeeded
>   congratulations :)
> ```

**Review by richm — APPROVED** [review]
lgtm

**Pull request merged**
