### PR TITLE
Increase memory of tests

### PR DESCRIPTION
**Pull request by sergio-correia**
We were experiencing failures in CI due to OOM errors, so let's increase
the amount of memory used when running the tests.

Additionally, to help us investigate further issues, the tests now display 
the facts gathered during the setup phase, and `run_cryptsetup()` runs 
with `--debug`, so that it can display extra information in case it fails.

### CODE REVIEW

**Comment by richm** [comment]
@sergio-correia does that debug output give any clues?

**Comment by sergio-correia** [comment]
> @sergio-correia pass! so maybe the problem is that the test needs more ram - in which case just turn this PR into a "real" PR

Yep. With `--debug` it gave some hints to be memory-related and by displaying the full facts I could check how much memory we had in the CI machine. After reducing the amount of memory locally, I could reproduce the issue and get an OOM error.

Finally, by using your suggestion to increase memory of the tests (thanks, btw), the issue was gone. Let me update this PR slightly and we can probably merge it.

**Comment by richm** [comment]
@sergio-correia please rebase this PR to resolve conflicts

**Comment by sergio-correia** [comment]
@richm: I have rebased it

**Pull request merged**
